{
 "title": "PV Dive 2",
 "description": "marine info of cabrillo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "period_name",
    "label": "Period",
    "query": "select period_name, w_swell_ft  from dive where time > now() - 9m group by \"period_name\""
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$period_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "period_name" },
  {
   "title": "Cabrillo",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "content": ">  {{value}}\n" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"detail_s\" where period_name =~/$period_name$/  AND location =~ /Cabrillo$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "swell",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 3 },
   "options": { "content": "### {{value}}" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_swell_s\" where period_name =~/$period_name$/  and location =~ /Cabrillo$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Malaga",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 3 },
   "options": { "content": ">  {{value}}\n" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"detail_s\" where period_name =~/$period_name$/  AND location =~ /Malaga$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "swell",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 3 },
   "options": { "content": "### {{value}}" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_swell_s\" where period_name =~/$period_name$/  and location =~ /Malaga$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redondo",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "options": { "content": ">  {{value}}\n" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"detail_s\" where period_name =~/$period_name$/  AND location =~ /Redondo$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "swell",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 1, "x": 14, "y": 3 },
   "options": { "content": "### {{value}}" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_swell_s\" where period_name =~/$period_name$/  and location =~ /Redondo$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "weather",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 5 },
   "options": {
    "content": "{{#if (eq value \"Sunny\")}}\n <span style=\"color:green\"> {{value}} </span>\n{{else}}\n <span style=\"color:yellow\"> {{value}} </span>\n{{/if}}\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_summary\" where period_name =~/$period_name$/  AND location =~ /Cabrillo$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "weather",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 5 },
   "options": {
    "content": "{{#if (eq value \"Sunny\")}}\n <span style=\"color:green\"> {{value}} </span>\n{{else}}\n <span style=\"color:yellow\"> {{value}} </span>\n{{/if}}\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_summary\" where period_name =~/$period_name$/  AND location =~ /Malaga$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "weather",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 1, "x": 14, "y": 5 },
   "options": {
    "content": "{{#if (eq value \"Sunny\")}}\n <span style=\"color:green\"> {{value}} </span>\n{{else}}\n <span style=\"color:yellow\"> {{value}} </span>\n{{/if}}\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_summary\" where period_name =~/$period_name$/  AND location =~ /Redondo$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}