{
 "title": "PV Dive",
 "description": "marine info of cabrillo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Site",
    "query": "show tag values with key=\"location\""
   },
   {
    "name": "period_name",
    "label": "Period",
    "query": "select period_name, w_swell_ft  from dive where time > now() - 9m group by \"period_name\""
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 0 },
   "options": {
    "content": "\n{{#if (eq value \"Cabrillo\")}}\n###\n ### [link to weather.gov->{{value}}](https://marine.weather.gov/MapClick.php?lon=-118.28481&lat=33.70772#.YknqXpPYqBQ\") \n{{/if}}\n\n{{#if (eq value \"Malaga\")}}\n###\n ### [link to weather.gov->{{value}}](https://marine.weather.gov/MapClick.php?lon=-118.39739&lat=33.80322#.YkuD7ZPYqBQ) \n{{/if}}\n\n{{#if (eq value \"Redondo\")}}\n###\n ### [link to weather.gov->{{value}} Beach](https://marine.weather.gov/MapClick.php?lon=-118.39165&lat=33.83646#.Yku_TpPMKBQ\") \n{{/if}}"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"location\" where location =~/$location$/  AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$period_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "period_name" },
  {
   "title": "swell (ft)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select w_swell_ft from dive where period_name =~/$period_name$/ and location =~ /$location$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "swell",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "options": { "content": "\n### {{value}}" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_swell_s\" where period_name =~/$period_name$/  and location =~ /$location$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "wind (kt)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select w_wind_kt from dive where period_name =~/$period_name$/ and location =~ /$location$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "weather",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "options": {
    "content": "{{#if (eq value \"Sunny\")}}\n ##  <span style=\"color:green\"> {{value}} </span>\n{{else}}\n ##  <span style=\"color:yellow\"> {{value}} </span>\n{{/if}}\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_summary\" where period_name =~/$period_name$/  AND location =~ /$location$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "detail forecast",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "options": { "content": ">  {{value}}\n" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"detail_s\" where period_name =~/$period_name$/  AND location =~ /$location$/ AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "options": { "content": "\n### {{value}}" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values with key=\"w_wind_s\" where period_name =~/$period_name$/  and location =~ /$location$/  AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}